#!/usr/bin/env node
/**
 * Fraga MCP HTTP Server — roda no servidor Hetzner, expõe ferramentas via HTTPS.
 */
import{createServer}from"http";import{exec}from"child_process";import{promisify}from"util";import{writeFileSync}from"fs";
const execAsync=promisify(exec);
const PORT=parseInt(process.env.MCP_PORT||"4001");
const SECRET=process.env.MCP_SECRET||"";
const CWD="/opt/fraga-dashboard";
if(!SECRET){console.error("[MCP] MCP_SECRET nao definido");process.exit(1)}
async function run(cmd,cwd=CWD,timeout=120000){try{const{stdout,stderr}=await execAsync(cmd,{cwd,timeout,maxBuffer:5*1024*1024,env:{...process.env,NODE_ENV:"production"}});return{ok:true,out:(stdout||"").trim(),err:(stderr||"").trim()}}catch(e){return{ok:false,out:(e.stdout||"").trim(),err:(e.stderr||e.message||"").trim()}}}
function fmt(r){let t=r.out;if(r.err)t+=(t?"\n\nSTDERR:\n":"")+r.err;return t||(r.ok?"(sem saida)":"Falhou.")}
const TOOLS=[{name:"fraga_exec",description:"Executa bash no servidor Fraga.",inputSchema:{type:"object",properties:{command:{type:"string"},cwd:{type:"string"}},required:["command"]}},{name:"fraga_pm2",description:"PM2: list,restart,logs,save.",inputSchema:{type:"object",properties:{action:{type:"string",enum:["list","restart","logs","save"]},process:{type:"string"},lines:{type:"number"}},required:["action"]}},{name:"fraga_deploy",description:"Deploy: git pull->build->restart.",inputSchema:{type:"object",properties:{branch:{type:"string"},skip_install:{type:"boolean"}}}},{name:"fraga_nginx",description:"Nginx: status,reload,test,show-config.",inputSchema:{type:"object",properties:{action:{type:"string",enum:["status","reload","test","show-config"]},site:{type:"string"}},required:["action"]}},{name:"fraga_read_file",description:"Le arquivo no servidor.",inputSchema:{type:"object",properties:{path:{type:"string"},lines:{type:"number"}},required:["path"]}},{name:"fraga_write_file",description:"Escreve arquivo no servidor.",inputSchema:{type:"object",properties:{path:{type:"string"},content:{type:"string"}},required:["path","content"]}}];
async function callTool(name,args={}){if(name==="fraga_exec")return fmt(await run(args.command,args.cwd||CWD,120000));if(name==="fraga_pm2"){const p=args.process||"fraga-dashboard";const l=args.lines||50;const c={list:"pm2 list",restart:`pm2 restart ${p} --update-env && pm2 list`,logs:`pm2 logs ${p} --lines ${l} --nostream`,save:"pm2 save --force"};return fmt(await run(c[args.action]||"pm2 list",CWD,90000))}if(name==="fraga_deploy"){const b=args.branch||"main";const steps=[`git pull origin ${b}`,...(args.skip_install?[]:["pnpm install --frozen-lockfile"]),"NODE_ENV=production pnpm run build","pm2 restart fraga-dashboard --update-env","pm2 save --force","echo '=== Deploy OK ==='","pm2 list"];return fmt(await run(steps.join(" && "),CWD,300000))}if(name==="fraga_nginx"){const c={status:"systemctl status nginx --no-pager | head -20",reload:"nginx -t && systemctl reload nginx && echo OK",test:"nginx -t","show-config":args.site?`cat /etc/nginx/sites-enabled/${args.site}`:"cat /etc/nginx/sites-enabled/*"};return fmt(await run(c[args.action]||"nginx -t","/",30000))}if(name==="fraga_read_file"){const c=args.lines?`tail -n ${args.lines} ${JSON.stringify(args.path)}`:`cat ${JSON.stringify(args.path)}`;return fmt(await run(c,"/",30000))}if(name==="fraga_write_file"){writeFileSync(args.path,args.content,"utf8");return`Salvo: ${args.path}`}return`Desconhecida: ${name}`}
const SESSIONS=new Map();
function jr(id,r){return{jsonrpc:"2.0",id,result:r}}
async function hrpc(msg,sid){const{id,method,params={}}=msg;if(method==="initialize"){SESSIONS.set(sid,1);return jr(id,{protocolVersion:"2024-11-05",capabilities:{tools:{}},serverInfo:{name:"fraga-server",version:"1.0.0"}})}if(method==="notifications/initialized")return null;if(method==="ping")return jr(id,{});if(method==="tools/list")return jr(id,{tools:TOOLS});if(method==="tools/call"){const{name,arguments:a}=params;try{const t=await callTool(name,a);return jr(id,{content:[{type:"text",text:t}],isError:false})}catch(e){return jr(id,{content:[{type:"text",text:String(e)}],isError:true})}}return jr(id,{error:`Not found: ${method}`})}
const server=createServer(async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type,Authorization,Mcp-Session-Id");res.setHeader("Access-Control-Allow-Methods","POST,GET,DELETE,OPTIONS");if(req.method==="OPTIONS"){res.writeHead(200);res.end();return}const auth=req.headers["authorization"]||"";if(!auth.startsWith("Bearer ")||auth.slice(7)!==SECRET){res.writeHead(401,{"Content-Type":"application/json"});res.end(JSON.stringify({error:"Unauthorized"}));return}if(req.method!=="POST"){res.writeHead(405);res.end();return}let body="";for await(const c of req)body+=c;let msg;try{msg=JSON.parse(body)}catch{res.writeHead(400);res.end();return}const sid=req.headers["mcp-session-id"]||"default";const isArr=Array.isArray(msg);const msgs=isArr?msg:[msg];const results=[];for(const m of msgs){const r=await hrpc(m,sid);if(r)results.push(r)}res.writeHead(200,{"Content-Type":"application/json"});res.end(JSON.stringify(isArr?results:results[0]||{}))});
server.listen(PORT,"127.0.0.1",()=>{console.log(`[Fraga MCP] Rodando em http://127.0.0.1:${PORT}`)});
